const staticDestination = [
  {
    name: "Orchha",
    name_hi: "ओरछा",
    img: "jhansi.jpg",
    desc: "A key city in Uttar Pradesh’s Bundelkhand region, Jhansi is steeped in history...",
    images: ["panna.jpg", "jhansi6.jpg", "orchha3.jpg"],
    location:"Orchha",
    slug: "orchha",
    type: "destination",
  },
  {
    name: "Datia",
    name_hi: "दतिया",
    img: "datia.jpg",
    desc: "A key city in Uttar Pradesh’s Bundelkhand region...",
    slug: "datia",
    location:"Datia",
    type: "destination",
    images: ["orchha3.jpg", "bandha.jpg", "jhansi6.jpg"],
  },
  {
    name: "Chanderi",
    name_hi: "चंदेरी",
    img: "jhansi2.jpg",
    desc: "A key city in Uttar Pradesh’s Bundelkhand region...",
    slug: "chanderi",
    location:"Chanderi",
    type: "destination",
    images: ["orchha3.jpg", "bandha.jpg", "jhansi6.jpg"],
  },
  {
    name: "Jhansi",
    name_hi: "झाँसी",
    img: "jhansi6.jpg",
    desc: "A key city in Uttar Pradesh’s Bundelkhand region...",
    slug: "jhansi",
    location:"Jhansi",
    type: "destination",
    images: ["orchha3.jpg", "bandha.jpg", "jhansi6.jpg"],
  },
  {
    name: "Tikamgarh",
    name_hi: "टीकमगढ़",
    img: "jhansi3.jpg",
    desc: "A key city in Uttar Pradesh’s Bundelkhand region...",
    slug: "tikamgarh",
    location:"Tikamgarh",
    type: "destination",
    images: ["orchha3.jpg", "bandha.jpg", "jhansi6.jpg"],
  },
];

export default staticDestination;